apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: aws-load-balancer-controller
    repoURL: https://aws.github.io/eks-charts
    targetRevision: 1.14.1
    helm:
      releaseName: aws-load-balancer-controller
      valuesObject:
        clusterName: CLUSTER_NAME_PLACEHOLDER
        region: REGION_PLACEHOLDER
        vpcId: VPC_ID_PLACEHOLDER
        serviceAccount:
          create: true
          name: aws-load-balancer-controller
          annotations:
            eks.amazonaws.com/role-arn: LB_ROLE_ARN_PLACEHOLDER
        replicaCount: 1
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 256Mi
        enableServiceMutatorWebhook: false
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
